name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      
      - name: Setup Python (for native dependencies)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      
      - name: Build application (skip typecheck)
        run: pnpm exec electron-vite build
      
      - name: Build for macOS (arm64 + x64)
        if: matrix.os == 'macos-latest'
        run: pnpm exec electron-builder --mac
      
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: pnpm exec electron-builder --win
      
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libgbm1 libasound2t64 || sudo apt-get install -y libasound2
      
      - name: Fix binary permissions before build
        if: matrix.os == 'ubuntu-latest'
        run: |
          find node_modules/.pnpm -type f -name "app-builder" -exec chmod +x {} \;
          find node_modules/.pnpm -type f -name "fpm" -exec chmod +x {} \; 2>/dev/null || true
      
      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: pnpm exec electron-builder --linux AppImage
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/*
          retention-days: 7

  release:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get version
        id: get_version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist
      
      - name: List artifacts
        run: |
          echo "Build artifacts:"
          find dist -type f -name "*.zip" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.snap" -o -name "*.exe" || true
      
      - name: Filter artifacts (keep only required files)
        run: |
          mkdir -p dist-filtered
          # Keep only: dmg, arm64-mac.zip, mac.zip, exe, AppImage
          find dist -type f \( \
            -name "*.dmg" \
            -o -name "local-termius-plus-*.dmg" \
            -o -name "*-arm64-mac.zip" \
            -o -name "*-mac.zip" \
            -o -name "*.exe" \
            -o -name "*.AppImage" \
          \) -exec cp {} dist-filtered/ \;
          echo "Filtered artifacts:"
          ls -lh dist-filtered/
      
      - name: Wait to avoid rate limiting
        run: sleep 10
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          files: |
            dist-filtered/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Retry Create Release on failure
        if: failure()
        run: sleep 60
      
      - name: Create Release (Retry)
        if: failure()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          files: |
            dist-filtered/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

